github.com:
    users:
        mexsrc:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: mexsrc
